name: miraca_energy_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - requests=2.31.0
  - shapely=2.0.5
  - pip
  - pip:
      - pandapower==2.14.11
      - geopandas==0.14.4	